# MNote this is an example. 
# Your NUT server may need to moify settings depending on what version it is running, etc. 
# EDIT THE IP address BELOW: Change xxx.xxx.xxx.xxx to the IP you reserved for your NUT server (e.g. Synology NAS)
# "monuser" is the NUT server usernaame and "secret" is the NUT password.
# For synolgy, leave them as they are unless Synology says otherwise. 
MONITOR ups@xxx.xxx.xxx.xxx 1 monuser secret secondary
MINSUPPLIES 1
# To basically restart. may restartt if the battery still has power so not recommended. 
# SHUTDOWNCMD "sudo sync; sudo sync; sudo sync; sudo shutdown -h now"
# To shut down completely and stay down until physically powered back on
SHUTDOWNCMD "sudo sync; sudo sync; sudo sync; sudo shutdown -P now"
POLLFREQ 5
POLLFREQALERT 5
HOSTSYNC 15
DEADTIME 15
