# EDIT THE IP BELOW: Change xxx.xxx.xxx.xxx to the IP you reserved for your NUT server (e.g. Synology NAS)
MONITOR ups@xxx.xxx.xxx.xxx monuser secret secondary
MINSUPPLIES 1
# To basically restart. may restartt if the battery still has power so not recommended. 
# SHUTDOWNCMD "sudo sync; sudo sync; sudo sync; sudo shutdown -h now"
# To shut down completely and stay down until physically powered back on
SHUTDOWNCMD "sudo sync; sudo sync; sudo sync; sudo shutdown -P now"
POLLFREQ 5
POLLFREQALERT 5
HOSTSYNC 15
DEADTIME 15
