# EDIT THE IP BELOW: Change xxx.xxx.xxx.xxx to the IP you reserved for your Synology NAS
MONITOR ups@xxx.xxx.xxx.xxx monuser secret secondary
MINSUPPLIES 1
SHUTDOWNCMD "sudo sync; sudo sync; sudo sync; sudo shutdown -h now"
POLLFREQ 5
POLLFREQALERT 5
HOSTSYNC 15
DEADTIME 15
